name: flutter_application_1
description: "App de finanças pessoais (controle de receitas e despesas)"
publish_to: "none" # porque é um app local de aula

version: 1.0.0+1

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  # Estado global
  provider: ^6.0.5

  # Banco de dados local
  sqflite: ^2.3.0
  path: ^1.9.0

  # Preferências simples (tema, nome do usuário, moeda)
  shared_preferences: ^2.2.2

  # Gráficos para o dashboard
  fl_chart: ^0.68.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
